[build-system]
requires = ["setuptools>=62.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-arizona"
description = "Tree-sitter parser for Arizona language (.herl files) - HTML with embedded Erlang code"
version = "0.1.0"
keywords = ["incremental", "parsing", "tree-sitter", "arizona"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
authors = [{ name = "William Fank Thomé", email = "willilamthome@hotmail.com" }]
requires-python = ">=3.10"
license.text = " Apache-2.0"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/arizona-framework/tree-sitter-arizona"
Funding = "https://github.com/sponsors/williamthome"

[project.optional-dependencies]
core = ["tree-sitter~=0.24"]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
